/**
 * @license
 * lodash 3.10.1 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash include="isEmpty,get,assign,forEach,isUndefined,defaultsDeep,debounce" -p`
 */
;(function(){function t(t){return!!t&&typeof t=="object"}function n(){}function r(t,n){for(var r=-1,e=t.length;++r<e&&false!==n(t[r],r,t););return t}function e(t,n,r){r||(r={});for(var e=-1,o=n.length;++e<o;){var u=n[e];r[u]=t[u]}return r}function o(t,n){return it(t,n,E)}function u(n,e,o,c,i){if(!m(n))return n;var a=l(e)&&(ft(e)||O(e)),f=a?T:pt(e);return r(f||e,function(r,s){if(f&&(s=r,r=e[s]),t(r)){c||(c=[]),i||(i=[]);t:{for(var p=s,y=c,b=i,g=y.length,h=e[p];g--;)if(y[g]==h){n[p]=b[g];break t}var g=n[p],j=o?o(g,h,p,n,e):T,m=j===T;
if(m)if(j=h,l(h)&&(ft(h)||O(h)))if(ft(g))j=g;else if(l(g)){var j=void 0,d=-1,A=g.length;for(j||(j=Array(A));++d<A;)j[d]=g[d]}else j=[];else w(h)||v(h)?j=v(g)?x(g):w(g)?g:{}:m=false;y.push(h),b.push(j),m?n[p]=u(j,h,o,y,b):(j===j?j!==g:g===g)&&(n[p]=j)}}else p=n[s],y=o?o(p,r,s,n,e):T,(b=y===T)&&(y=r),y===T&&(!a||s in n)||!b&&(y===y?y===p:p!==p)||(n[s]=y)}),n}function c(t,n,r){if(typeof t!="function")return S;if(n===T)return t;switch(r){case 1:return function(r){return t.call(n,r)};case 3:return function(r,e,o){
return t.call(n,r,e,o)};case 4:return function(r,e,o,u){return t.call(n,r,e,o,u)};case 5:return function(r,e,o,u,c){return t.call(n,r,e,o,u,c)}}return function(){return t.apply(n,arguments)}}function i(t){return h(function(n,r){var e=-1,o=null==n?0:r.length,u=2<o?r[o-2]:T,i=2<o?r[2]:T,a=1<o?r[o-1]:T;if(typeof u=="function"?(u=c(u,a,5),o-=2):(u=typeof a=="function"?a:T,o-=u?1:0),a=i){var a=r[0],s=r[1];if(m(i)){var p=typeof s;("number"==p?l(i)&&f(s,i.length):"string"==p&&s in i)?(i=i[s],a=a===a?a===i:i!==i):a=false;
}else a=false}for(a&&(u=3>o?T:u,o=1);++e<o;)(i=r[e])&&t(n,i,u);return n})}function a(t,n){var r=null==t?T:t[n];return d(r)?r:T}function l(t){return null!=t&&s(at(t))}function f(t,n){return t=typeof t=="number"||L.test(t)?+t:-1,n=null==n?ot:n,-1<t&&0==t%1&&t<n}function s(t){return typeof t=="number"&&-1<t&&0==t%1&&t<=ot}function p(t,n){return t===T?n:st(t,n,p)}function y(t){for(var n=E(t),r=n.length,e=r&&t.length,o=!!e&&s(e)&&(ft(t)||v(t)||A(t)),u=-1,c=[];++u<r;){var i=n[u];(o&&f(i,e)||K.call(t,i))&&c.push(i);
}return c}function b(t){if(n.support.unindexedChars&&A(t)){for(var r=-1,e=t.length,o=Object(t);++r<e;)o[r]=t.charAt(r);return o}return m(t)?t:Object(t)}function g(t){if(ft(t))return t;var n=[];return(null==t?"":t+"").replace(F,function(t,r,e,o){n.push(e?o.replace(U,"$1"):r||t)}),n}function h(t,n){if(typeof t!="function")throw new TypeError(P);return n=rt(n===T?t.length-1:+n||0,0),function(){for(var r=arguments,e=-1,o=rt(r.length-n,0),u=Array(o);++e<o;)u[e]=r[n+e];switch(n){case 0:return t.call(this,u);
case 1:return t.call(this,r[0],u);case 2:return t.call(this,r[0],r[1],u)}for(o=Array(n+1),e=-1;++e<n;)o[e]=r[e];return o[n]=u,t.apply(this,o)}}function v(n){return t(n)&&l(n)&&K.call(n,"callee")&&!Y.call(n,"callee")}function j(t){return m(t)&&Q.call(t)==$}function m(t){var n=typeof t;return!!t&&("object"==n||"function"==n)}function d(n){return null==n?false:j(n)?X.test(J.call(n)):t(n)&&(q(n)?X:C).test(n)}function w(r){var e;if(!t(r)||Q.call(r)!=k||q(r)||v(r)||!(K.call(r,"constructor")||(e=r.constructor,
typeof e!="function"||e instanceof e)))return false;var u;return n.support.ownLast?(o(r,function(t,n,r){return u=K.call(r,n),false}),false!==u):(o(r,function(t,n){u=n}),u===T||K.call(r,u))}function A(n){return typeof n=="string"||t(n)&&Q.call(n)==D}function O(n){return t(n)&&s(n.length)&&!!R[Q.call(n)]}function x(t){return e(t,E(t))}function E(t){if(null==t)return[];m(t)||(t=Object(t));for(var r=t.length,e=n.support,r=r&&s(r)&&(ft(t)||v(t)||A(t))&&r||0,o=t.constructor,u=-1,o=j(o)&&o.prototype||G,c=o===t,i=Array(r),a=0<r,l=e.enumErrorProps&&(t===z||t instanceof Error),p=e.enumPrototypes&&j(t);++u<r;)i[u]=u+"";
for(var y in t)p&&"prototype"==y||l&&("message"==y||"name"==y)||a&&f(y,r)||"constructor"==y&&(c||!K.call(t,y))||i.push(y);if(e.nonEnumShadows&&t!==G)for(r=t===H?D:t===z?I:Q.call(t),e=ut[r]||ut[k],r==k&&(o=G),r=N.length;r--;)y=N[r],u=e[y],c&&u||(u?!K.call(t,y):t[y]===o[y])||i.push(y);return i}function S(t){return t}var T,P="Expected a function",I="[object Error]",$="[object Function]",k="[object Object]",D="[object String]",F=/[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\n\\]|\\.)*?)\2)\]/g,U=/\\(\\)?/g,C=/^\[object .+?Constructor\]$/,L=/^\d+$/,N="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),R={};
R["[object Float32Array]"]=R["[object Float64Array]"]=R["[object Int8Array]"]=R["[object Int16Array]"]=R["[object Int32Array]"]=R["[object Uint8Array]"]=R["[object Uint8ClampedArray]"]=R["[object Uint16Array]"]=R["[object Uint32Array]"]=true,R["[object Arguments]"]=R["[object Array]"]=R["[object ArrayBuffer]"]=R["[object Boolean]"]=R["[object Date]"]=R[I]=R[$]=R["[object Map]"]=R["[object Number]"]=R[k]=R["[object RegExp]"]=R["[object Set]"]=R[D]=R["[object WeakMap]"]=false;var _={"function":true,object:true
},B=_[typeof exports]&&exports&&!exports.nodeType&&exports,M=_[typeof module]&&module&&!module.nodeType&&module,W=_[typeof self]&&self&&self.Object&&self,V=_[typeof window]&&window&&window.Object&&window,_=M&&M.exports===B&&B,W=B&&M&&typeof global=="object"&&global&&global.Object&&global||V!==(this&&this.window)&&V||W||this,q=function(){try{Object({toString:0}+"")}catch(t){return function(){return false}}return function(t){return typeof t.toString!="function"&&typeof(t+"")=="string"}}(),V=Array.prototype,z=Error.prototype,G=Object.prototype,H=String.prototype,J=Function.prototype.toString,K=G.hasOwnProperty,Q=G.toString,X=RegExp("^"+J.call(K).replace(/[\\^$.*+?()[\]{}|]/g,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),Y=G.propertyIsEnumerable,Z=V.splice,tt=a(Array,"isArray"),nt=a(Object,"keys"),rt=Math.max,et=a(Date,"now"),ot=9007199254740991,ut={};
ut["[object Array]"]=ut["[object Date]"]=ut["[object Number]"]={constructor:true,toLocaleString:true,toString:true,valueOf:true},ut["[object Boolean]"]=ut[D]={constructor:true,toString:true,valueOf:true},ut[I]=ut[$]=ut["[object RegExp]"]={constructor:true,toString:true},ut[k]={constructor:true},r(N,function(t){for(var n in ut)if(K.call(ut,n)){var r=ut[n];r[t]=K.call(r,t)}});var ct=n.support={};!function(t){var n=function(){this.x=t},r={0:t,length:t},e=[];n.prototype={valueOf:t,y:t};for(var o in new n)e.push(o);ct.enumErrorProps=Y.call(z,"message")||Y.call(z,"name"),
ct.enumPrototypes=Y.call(n,"prototype"),ct.nonEnumShadows=!/valueOf/.test(e),ct.ownLast="x"!=e[0],ct.spliceObjects=(Z.call(r,0,1),!r[0]),ct.unindexedChars="xx"!="x"[0]+Object("x")[0]}(1,0);var V=function(t,n){return function(r,e){var o=r?at(r):0;if(!s(o))return t(r,e);for(var u=n?o:-1,c=b(r);(n?u--:++u<o)&&false!==e(c[u],u,c););return r}}(function(t,n){return it(t,n,pt)}),it=function(t){return function(n,r,e){var o=b(n);e=e(n);for(var u=e.length,c=t?u:-1;t?c--:++c<u;){var i=e[c];if(false===r(o[i],i,o))break;
}return n}}(),at=function(t){return function(n){return null==n?T:b(n)[t]}}("length"),V=function(t,n){return function(r,e,o){return typeof e=="function"&&o===T&&ft(r)?t(r,e):n(r,c(e,o,3))}}(r,V),lt=et||function(){return(new Date).getTime()},ft=tt||function(n){return t(n)&&s(n.length)&&"[object Array]"==Q.call(n)},st=i(u),tt=i(function(t,n,r){if(r)for(var o=-1,u=pt(n),c=u.length;++o<c;){var i=u[o],a=t[i],l=r(a,n[i],i,t,n);(l===l?l===a:a!==a)&&(a!==T||i in t)||(t[i]=l)}else t=null==n?t:e(n,pt(n),t);return t;
}),et=function(t,n){return h(function(r){var e=r[0];return null==e?e:(r.push(n),t.apply(T,r))})}(st,p),pt=nt?function(t){var r=null==t?T:t.constructor;return typeof r=="function"&&r.prototype===t||(typeof t=="function"?n.support.enumPrototypes:l(t))?y(t):m(t)?nt(t):[]}:y;n.assign=tt,n.debounce=function(t,n,r){function e(n,r){r&&clearTimeout(r),a=p=y=T,n&&(b=lt(),l=t.apply(s,i),p||a||(i=s=T))}function o(){var t=n-(lt()-f);0>=t||t>n?e(y,a):p=setTimeout(o,t)}function u(){e(h,p)}function c(){if(i=arguments,
f=lt(),s=this,y=h&&(p||!v),false===g)var r=v&&!p;else{a||v||(b=f);var e=g-(f-b),c=0>=e||e>g;c?(a&&(a=clearTimeout(a)),b=f,l=t.apply(s,i)):a||(a=setTimeout(u,e))}return c&&p?p=clearTimeout(p):p||n===g||(p=setTimeout(o,n)),r&&(c=true,l=t.apply(s,i)),!c||p||a||(i=s=T),l}var i,a,l,f,s,p,y,b=0,g=false,h=true;if(typeof t!="function")throw new TypeError(P);if(n=0>n?0:+n||0,true===r)var v=true,h=false;else m(r)&&(v=!!r.leading,g="maxWait"in r&&rt(+r.maxWait||0,n),h="trailing"in r?!!r.trailing:h);return c.cancel=function(){
p&&clearTimeout(p),a&&clearTimeout(a),b=0,a=p=y=T},c},n.defaultsDeep=et,n.forEach=V,n.keys=pt,n.keysIn=E,n.merge=st,n.restParam=h,n.toPlainObject=x,n.each=V,n.extend=tt,n.get=function(t,n,r){if(null==t)t=T;else{var e=g(n);if(n+="",null==t)t=void 0;else{t=b(t),n!==T&&n in t&&(e=[n]),n=0;for(var o=e.length;null!=t&&n<o;)t=b(t)[e[n++]];t=n&&n==o?t:T}}return t===T?r:t},n.identity=S,n.isArguments=v,n.isArray=ft,n.isEmpty=function(n){return null==n?true:l(n)&&(ft(n)||A(n)||v(n)||t(n)&&j(n.splice))?!n.length:!pt(n).length;
},n.isFunction=j,n.isNative=d,n.isObject=m,n.isPlainObject=w,n.isString=A,n.isTypedArray=O,n.isUndefined=function(t){return t===T},n.now=lt,n.VERSION="3.10.1",typeof define=="function"&&typeof define.amd=="object"&&define.amd?(W._=n, define(function(){return n})):B&&M?_?(M.exports=n)._=n:B._=n:W._=n}).call(this);