/**
 * @license
 * lodash 3.10.1 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash include="isEmpty,get,assign,forEach,isUndefined,defaultsDeep" -p`
 */
;(function(){function w(a){return!!a&&typeof a=="object"}function c(){}function Q(a,b){for(var d=-1,h=a.length;++d<h&&false!==b(a[d],d,a););return a}function Z(a,b,d){d||(d={});for(var h=-1,f=b.length;++h<f;){var s=b[h];d[s]=a[s]}return d}function $(a,b){aa(a,b,K)}function ba(a,b,d,h,f){if(!t(a))return a;var s=x(b)&&(v(b)||R(b)),ca=s?g:u(b);Q(ca||b,function(k,c){ca&&(c=k,k=b[c]);if(w(k)){h||(h=[]);f||(f=[]);a:{for(var e=c,n=h,m=f,q=n.length,l=b[e];q--;)if(n[q]==l){a[e]=m[q];break a}var q=a[e],
r=d?d(q,l,e,a,b):g,t=r===g;if(t)if(r=l,x(l)&&(v(l)||R(l))){var p;if(v(q))p=q;else if(x(q)){var r=-1,u=q.length;for(p||(p=Array(u));++r<u;)p[r]=q[r]}else p=[];r=p}else S(l)||y(l)?r=y(q)?da(q):S(q)?q:{}:t=false;n.push(l);m.push(r);if(t)a[e]=ba(r,l,d,n,m);else if(r===r?r!==q:q===q)a[e]=r}}else e=a[c],n=d?d(e,k,c,a,b):g,(m=n===g)&&(n=k),n===g&&(!s||c in a)||!m&&(n===n?n===e:e!==e)||(a[c]=n)});return a}function ea(a,b,d){if(typeof a!="function")return fa;if(b===g)return a;switch(d){case 1:return function(d){return a.call(b,
d)};case 3:return function(d,f,s){return a.call(b,d,f,s)};case 4:return function(d,f,s,c){return a.call(b,d,f,s,c)};case 5:return function(d,f,s,c,e){return a.call(b,d,f,s,c,e)}}return function(){return a.apply(b,arguments)}}function ga(a){return T(function(b,d){var h=-1,f=null==b?0:d.length,c=2<f?d[f-2]:g,e=2<f?d[2]:g,k=1<f?d[f-1]:g;typeof c=="function"?(c=ea(c,k,5),f-=2):(c=typeof k=="function"?k:g,f-=c?1:0);if(k=e){var k=d[0],l=d[1];if(t(e)){var m=typeof l;("number"==m?x(e)&&U(l,e.length):"string"==
m&&l in e)?(e=e[l],k=k===k?k===e:e!==e):k=false}else k=false}k&&(c=3>f?g:c,f=1);for(;++h<f;)(e=d[h])&&a(b,e,c);return b})}function ha(a,b){var d=null==a?g:a[b];return ia(d)?d:g}function x(a){return null!=a&&z(ja(a))}function U(a,b){a=typeof a=="number"||sa.test(a)?+a:-1;b=null==b?ka:b;return-1<a&&0==a%1&&a<b}function z(a){return typeof a=="number"&&-1<a&&0==a%1&&a<=ka}function la(a,b){return a===g?b:V(a,b,la)}function ma(a){for(var b=K(a),d=b.length,h=d&&a.length,f=!!h&&z(h)&&(v(a)||y(a)||E(a)),c=-1,e=[];++c<
d;){var k=b[c];(f&&U(k,h)||l.call(a,k))&&e.push(k)}return e}function F(a){if(c.support.unindexedChars&&E(a)){for(var b=-1,d=a.length,h=Object(a);++b<d;)h[b]=a.charAt(b);return h}return t(a)?a:Object(a)}function ta(a){if(v(a))return a;var b=[];(null==a?"":a+"").replace(ua,function(a,h,f,c){b.push(f?c.replace(va,"$1"):h||a)});return b}function T(a,b){if(typeof a!="function")throw new TypeError(wa);b=na(b===g?a.length-1:+b||0,0);return function(){for(var d=arguments,h=-1,f=na(d.length-b,0),c=Array(f);++h<
f;)c[h]=d[b+h];switch(b){case 0:return a.call(this,c);case 1:return a.call(this,d[0],c);case 2:return a.call(this,d[0],d[1],c)}f=Array(b+1);for(h=-1;++h<b;)f[h]=d[h];f[b]=c;return a.apply(this,f)}}function y(a){return w(a)&&x(a)&&l.call(a,"callee")&&!L.call(a,"callee")}function G(a){return t(a)&&A.call(a)==W}function t(a){var b=typeof a;return!!a&&("object"==b||"function"==b)}function ia(a){return null==a?false:G(a)?oa.test(pa.call(a)):w(a)&&(qa(a)?oa:xa).test(a)}function S(a){var b;if(!w(a)||A.call(a)!=
H||qa(a)||y(a)||!(l.call(a,"constructor")||(b=a.constructor,typeof b!="function"||b instanceof b)))return false;var d;if(c.support.ownLast)return $(a,function(a,b,c){d=l.call(c,b);return false}),false!==d;$(a,function(a,b){d=b});return d===g||l.call(a,d)}function E(a){return typeof a=="string"||w(a)&&A.call(a)==M}function R(a){return w(a)&&z(a.length)&&!!e[A.call(a)]}function da(a){return Z(a,K(a))}function K(a){if(null==a)return[];t(a)||(a=Object(a));for(var b=a.length,d=c.support,b=b&&z(b)&&(v(a)||y(a)||E(a))&&
b||0,h=a.constructor,f=-1,h=G(h)&&h.prototype||B,e=h===a,g=Array(b),k=0<b,p=d.enumErrorProps&&(a===N||a instanceof Error),u=d.enumPrototypes&&G(a);++f<b;)g[f]=f+"";for(var n in a)u&&"prototype"==n||p&&("message"==n||"name"==n)||k&&U(n,b)||"constructor"==n&&(e||!l.call(a,n))||g.push(n);if(d.nonEnumShadows&&a!==B)for(b=a===ya?M:a===N?X:A.call(a),d=m[b]||m[H],b==H&&(h=B),b=Y.length;b--;)n=Y[b],f=d[n],e&&f||(f?!l.call(a,n):a[n]===h[n])||g.push(n);return g}function fa(a){return a}var g,wa="Expected a function",
X="[object Error]",W="[object Function]",H="[object Object]",M="[object String]",ua=/[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\n\\]|\\.)*?)\2)\]/g,va=/\\(\\)?/g,xa=/^\[object .+?Constructor\]$/,sa=/^\d+$/,Y="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),e={};e["[object Float32Array]"]=e["[object Float64Array]"]=e["[object Int8Array]"]=e["[object Int16Array]"]=e["[object Int32Array]"]=e["[object Uint8Array]"]=e["[object Uint8ClampedArray]"]=
e["[object Uint16Array]"]=e["[object Uint32Array]"]=true;e["[object Arguments]"]=e["[object Array]"]=e["[object ArrayBuffer]"]=e["[object Boolean]"]=e["[object Date]"]=e[X]=e[W]=e["[object Map]"]=e["[object Number]"]=e[H]=e["[object RegExp]"]=e["[object Set]"]=e[M]=e["[object WeakMap]"]=false;var C={"function":true,object:true},I=C[typeof exports]&&exports&&!exports.nodeType&&exports,J=C[typeof module]&&module&&!module.nodeType&&module,O=C[typeof self]&&self&&self.Object&&self,p=C[typeof window]&&window&&
window.Object&&window,C=J&&J.exports===I&&I,O=I&&J&&typeof global=="object"&&global&&global.Object&&global||p!==(this&&this.window)&&p||O||this,qa=function(){try{Object({toString:0}+"")}catch(a){return function(){return false}}return function(a){return typeof a.toString!="function"&&typeof(a+"")=="string"}}(),p=Array.prototype,N=Error.prototype,B=Object.prototype,ya=String.prototype,pa=Function.prototype.toString,l=B.hasOwnProperty,A=B.toString,oa=RegExp("^"+pa.call(l).replace(/[\\^$.*+?()[\]{}|]/g,
"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),L=B.propertyIsEnumerable,za=p.splice,P=ha(Array,"isArray"),ra=ha(Object,"keys"),na=Math.max,ka=9007199254740991,m={};m["[object Array]"]=m["[object Date]"]=m["[object Number]"]={constructor:true,toLocaleString:true,toString:true,valueOf:true};m["[object Boolean]"]=m[M]={constructor:true,toString:true,valueOf:true};m[X]=m[W]=m["[object RegExp]"]={constructor:true,toString:true};m[H]={constructor:true};Q(Y,function(a){for(var b in m)if(l.call(m,
b)){var d=m[b];d[a]=l.call(d,a)}});var D=c.support={};(function(a){function b(){this.x=a}var d={0:a,length:a},c=[];b.prototype={valueOf:a,y:a};for(var f in new b)c.push(f);D.enumErrorProps=L.call(N,"message")||L.call(N,"name");D.enumPrototypes=L.call(b,"prototype");D.nonEnumShadows=!/valueOf/.test(c);D.ownLast="x"!=c[0];D.spliceObjects=(za.call(d,0,1),!d[0]);D.unindexedChars="xx"!="x"[0]+Object("x")[0]})(1,0);var aa=function(a){return function(b,d,c){var f=F(b);c=c(b);for(var e=c.length,g=a?e:-1;a?g--:
++g<e;){var k=c[g];if(false===d(f[k],k,f))break}return b}}(),ja=function(a){return function(b){return null==b?g:F(b)[a]}}("length"),p=function(a,b){return function(d,c,e){return typeof c=="function"&&e===g&&v(d)?a(d,c):b(d,ea(c,e,3))}}(Q,function(a,b){return function(d,c){var e=d?ja(d):0;if(!z(e))return a(d,c);for(var g=b?e:-1,l=F(d);(b?g--:++g<e)&&false!==c(l[g],g,l););return d}}(function(a,b){return aa(a,b,u)})),v=P||function(a){return w(a)&&z(a.length)&&"[object Array]"==A.call(a)},V=ga(ba),P=ga(function(a,
b,d){if(d)for(var c=-1,e=u(b),l=e.length;++c<l;){var m=e[c],k=a[m],p=d(k,b[m],m,a,b);(p===p?p===k:k!==k)&&(k!==g||m in a)||(a[m]=p)}else a=null==b?a:Z(b,u(b),a);return a}),Aa=function(a,b){return T(function(c){var e=c[0];if(null==e)return e;c.push(b);return a.apply(g,c)})}(V,la),u=ra?function(a){var b=null==a?g:a.constructor;return typeof b=="function"&&b.prototype===a||(typeof a=="function"?c.support.enumPrototypes:x(a))?ma(a):t(a)?ra(a):[]}:ma;c.assign=P;c.defaultsDeep=Aa;c.forEach=p;c.keys=u;c.keysIn=
K;c.merge=V;c.restParam=T;c.toPlainObject=da;c.each=p;c.extend=P;c.get=function(a,b,c){if(null==a)a=g;else{var e=ta(b);b+="";if(null!=a){a=F(a);b!==g&&b in a&&(e=[b]);b=0;for(var f=e.length;null!=a&&b<f;)a=F(a)[e[b++]];a=b&&b==f?a:g}else a=void 0}return a===g?c:a};c.identity=fa;c.isArguments=y;c.isArray=v;c.isEmpty=function(a){return null==a?true:x(a)&&(v(a)||E(a)||y(a)||w(a)&&G(a.splice))?!a.length:!u(a).length};c.isFunction=G;c.isNative=ia;c.isObject=t;c.isPlainObject=S;c.isString=E;c.isTypedArray=
R;c.isUndefined=function(a){return a===g};c.VERSION="3.10.1";typeof define=="function"&&typeof define.amd=="object"&&define.amd?(O._=c, define(function(){return c})):I&&J?C?(J.exports=c)._=c:I._=c:O._=c}.call(this));